registry_version: '1.0'
assets:
- id: normative_spec
  path: ../../../normative_spec.txt
  sha256: 5357914e11a2e77ae61fcf6a8b0e38465fef8bf74165122a52adfe3e389f19ad
  version: 1.0.0
  size_bytes: 35309
  last_modified: '2025-09-09T05:15:45.000000+00:00'
- id: system
  path: system.md
  sha256: f9de7a6b0312eca3ddf45e30b3e94a03c3bf479383a1427a67176738cca5798f
  version: 1.0.0
  size_bytes: 32950
  last_modified: '2025-09-09T20:59:05.878077+00:00'

# Phase 1 Matrix C Assets
- id: phase1_c_mechanical
  path: phase1/C/mechanical.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 1 mechanical construction for Matrix C
- id: phase1_c_interpreted
  path: phase1/C/interpreted.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 2 semantic interpretation for Matrix C
- id: phase1_c_lensed
  path: phase1/C/lensed.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 3 lens application for Matrix C

# Phase 1 Matrix F Assets
- id: phase1_f_mechanical
  path: phase1/F/mechanical.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 1 mechanical construction for Matrix F
- id: phase1_f_interpreted
  path: phase1/F/interpreted.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 2 semantic interpretation for Matrix F
- id: phase1_f_lensed
  path: phase1/F/lensed.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 3 lens application for Matrix F

# Phase 1 Matrix D Assets
- id: phase1_d_mechanical
  path: phase1/D/mechanical.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 1 mechanical construction for Matrix D (concatenation recipe)
- id: phase1_d_interpreted
  path: phase1/D/interpreted.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 2 addition resolution for Matrix D (no multiplication)
- id: phase1_d_lensed
  path: phase1/D/lensed.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 3 lens application for Matrix D

# Phase 1 Matrix X Assets
- id: phase1_x_mechanical
  path: phase1/X/mechanical.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 1 mechanical construction for Matrix X
- id: phase1_x_interpreted
  path: phase1/X/interpreted.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 2 semantic interpretation for Matrix X
- id: phase1_x_lensed
  path: phase1/X/lensed.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 3 lens application for Matrix X

# Phase 1 Matrix E Assets
- id: phase1_e_mechanical
  path: phase1/E/mechanical.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 1 mechanical construction for Matrix E
- id: phase1_e_interpreted
  path: phase1/E/interpreted.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 2 semantic interpretation for Matrix E
- id: phase1_e_lensed
  path: phase1/E/lensed.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Stage 3 lens application for Matrix E

# Phase 1 Matrix Z Assets
- id: phase1_z_lensed
  path: phase1/Z/lensed.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Station shift and lens application for Matrix Z (no interpreted stage)
- id: phase1_z_principles
  path: phase1/Z/principles.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: Principles extraction from Matrix Z

# Phase 1 Lens Catalog Generation
- id: phase1_lens_catalog_generation
  path: phase1/lens_catalog_generation.md
  sha256: 5ccbfe519bab6c501302c7e15be6472fb3c9c263f88bfc632f7b81348c379c4a
  version: 1.1.0
  size_bytes: 860
  last_modified: '2025-09-09T12:00:00.000000+00:00'
  description: Template for generating lens catalog for all stations

# Phase 1 Per-Matrix Lens Generation Assets
- id: phase1_c_generate_lenses
  path: phase1/C/generate_lenses.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: On-the-fly lens generation for Matrix C (Problem Statement)

- id: phase1_d_generate_lenses
  path: phase1/D/generate_lenses.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: On-the-fly lens generation for Matrix D (Objectives)

- id: phase1_f_generate_lenses
  path: phase1/F/generate_lenses.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: On-the-fly lens generation for Matrix F (Requirements)

- id: phase1_x_generate_lenses
  path: phase1/X/generate_lenses.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: On-the-fly lens generation for Matrix X (Verification)

- id: phase1_e_generate_lenses
  path: phase1/E/generate_lenses.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: On-the-fly lens generation for Matrix E (Evaluation)

- id: phase1_z_generate_lenses
  path: phase1/Z/generate_lenses.md
  sha256: pending_user_authoring
  version: 1.0.0
  description: On-the-fly lens generation for Matrix Z (Validation)